import os
from dotenv import load_dotenv
import re
from datetime import datetime

import resend

load_dotenv()

def send_email(markdown_body):
    resend.api_key = os.environ["RESEND_API_KEY"]

    today = datetime.now().strftime("%A, %B %-d, %Y")
    html_body = markdown_to_html(markdown_body)

    resend.Emails.send({
        "from": os.environ.get("EMAIL_FROM", "onboarding@resend.dev"),
        "to": [e.strip() for e in os.environ["EMAIL_TO"].split(",")],
        "subject": f"AI Agent Digest — {today}",
        "html": wrap_html(html_body, today),
    })


def markdown_to_html(md):
    md = re.sub(r"^### (.+)$", r'<h3 style="color:#1a1a2e;margin:18px 0 8px;">\1</h3>', md, flags=re.MULTILINE)
    md = re.sub(r"^## (.+)$", r'<h2 style="color:#1a1a2e;margin:24px 0 10px;">\1</h2>', md, flags=re.MULTILINE)
    md = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", md)
    md = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2" style="color:#4361ee;">\1</a>', md)
    md = re.sub(r"^- (.+)$", r'<li style="margin:4px 0;">\1</li>', md, flags=re.MULTILINE)
    md = re.sub(
        r"(<li[^>]*>.*</li>\n?)+",
        lambda m: f'<ul style="padding-left:20px;">{m.group(0)}</ul>',
        md,
    )
    md = re.sub(r"\n{2,}", "<br><br>", md)
    md = re.sub(r"\n", "<br>", md)
    return md


def wrap_html(body, date):
    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background:#f4f4f8;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <div style="max-width:640px;margin:0 auto;padding:32px 20px;">
    <div style="background:#1a1a2e;color:white;padding:24px 32px;border-radius:12px 12px 0 0;">
      <h1 style="margin:0;font-size:24px;">AI Agent Digest</h1>
      <p style="margin:6px 0 0;opacity:0.8;font-size:14px;">{date}</p>
    </div>
    <div style="background:white;padding:24px 32px;border-radius:0 0 12px 12px;line-height:1.6;color:#333;">
      {body}
    </div>
    <p style="text-align:center;color:#999;font-size:12px;margin-top:16px;">
      Generated by AI Agent Daily Digest
    </p>
  </div>
</body>
</html>"""
