import { Resend } from "resend";

export async function sendEmail(markdownBody) {
  const resend = new Resend(process.env.RESEND_API_KEY);

  const today = new Date().toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const htmlBody = markdownToHtml(markdownBody);

  const { error } = await resend.emails.send({
    from: process.env.EMAIL_FROM || "onboarding@resend.dev",
    to: process.env.EMAIL_TO.split(",").map((e) => e.trim()),
    subject: `AI Agent Digest — ${today}`,
    html: wrapHtml(htmlBody, today),
  });

  if (error) throw new Error(`Resend error: ${JSON.stringify(error)}`);
}

function markdownToHtml(md) {
  return md
    .replace(/^### (.+)$/gm, '<h3 style="color:#1a1a2e;margin:18px 0 8px;">$1</h3>')
    .replace(/^## (.+)$/gm, '<h2 style="color:#1a1a2e;margin:24px 0 10px;">$1</h2>')
    .replace(
      /\*\*(.+?)\*\*/g,
      "<strong>$1</strong>"
    )
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" style="color:#4361ee;">$1</a>')
    .replace(/^- (.+)$/gm, '<li style="margin:4px 0;">$1</li>')
    .replace(
      /(<li[^>]*>.*<\/li>\n?)+/g,
      (match) => `<ul style="padding-left:20px;">${match}</ul>`
    )
    .replace(/\n{2,}/g, "<br><br>")
    .replace(/\n/g, "<br>");
}

function wrapHtml(body, date) {
  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background:#f4f4f8;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <div style="max-width:640px;margin:0 auto;padding:32px 20px;">
    <div style="background:#1a1a2e;color:white;padding:24px 32px;border-radius:12px 12px 0 0;">
      <h1 style="margin:0;font-size:24px;">AI Agent Digest</h1>
      <p style="margin:6px 0 0;opacity:0.8;font-size:14px;">${date}</p>
    </div>
    <div style="background:white;padding:24px 32px;border-radius:0 0 12px 12px;line-height:1.6;color:#333;">
      ${body}
    </div>
    <p style="text-align:center;color:#999;font-size:12px;margin-top:16px;">
      Generated by AI Agent Daily Digest
    </p>
  </div>
</body>
</html>`;
}
